// @ts-check

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.

 @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
TechnicalDocumentsSidebar: [
  {
    type: 'autogenerated',
    dirName: 'dna-knowledge-base/technical-documentation'
  }
],
OnboardingDocumentsSidebar: [
  {
    type: 'autogenerated',
    dirName: 'dna-knowledge-base/onboarding-documents'
  }
],

// midas_sqt_sidebar: [
//   {
//     type: 'autogenerated',
//     dirName: 'midas/midas_sqt_manual'
//   }
// ],
coding_standards_sidebar: [
  {
    type: 'autogenerated',
    dirName: 'dna-knowledge-base/coding-standards'
  }
],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;